package com.health.calculator.bmi.tracker.export

import com.health.calculator.bmi.tracker.data.export.ExportDisclosurePolicy
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

class ExportDisclosurePolicyTest {
    @Test
    fun footerIdentifiesProvenanceAndNonClinicalPurpose() {
        val footer = ExportDisclosurePolicy.shareFooter()

        assertTrue(footer.contains("Generated by Health Metrics Tracker"))
        assertTrue(footer.contains("Informational wellness data"))
        assertTrue(footer.contains("Not a medical diagnosis"))
        assertTrue(footer.contains("does not diagnose"))
    }

    @Test
    fun appendToShareTextIsIdempotentForAlreadyDisclosedContent() {
        val content = "A saved wellness result"
        val disclosed = ExportDisclosurePolicy.appendToShareText(content)

        assertEquals(disclosed, ExportDisclosurePolicy.appendToShareText(disclosed))
        assertTrue(disclosed.startsWith(content))
    }

    @Test
    fun csvMetadataIsSmallAndSafeToPrepend() {
        val rows = ExportDisclosurePolicy.csvMetadataRows()

        assertEquals(3, rows.size)
        assertTrue(rows.all { it.startsWith("# ") })
        assertTrue(rows.joinToString("\n").lowercase().contains("not a medical diagnosis"))
    }
}
