package com.health.calculator.bmi.tracker.data.export

/**
 * Shared wording for files and text that leave the app.
 *
 * Keeping this in one place prevents a PDF, CSV, image, or text share from
 * accidentally looking like a clinical report or losing its provenance.
 */
object ExportDisclosurePolicy {
    const val APP_NAME = "Health Metrics Tracker"
    const val INFORMATIONAL_LABEL = "Informational wellness data"
    const val DIAGNOSIS_NOTICE = "Not a medical diagnosis"

    const val MEDICAL_DISCLAIMER =
        "This information is for personal tracking and general wellness education. " +
            "It does not diagnose, treat, or replace advice from a qualified healthcare professional."

    /** Footer for plain-text shares and the metadata shown beside file shares. */
    fun shareFooter(): String = buildString {
        appendLine("Generated by $APP_NAME")
        appendLine("$INFORMATIONAL_LABEL only — $DIAGNOSIS_NOTICE.")
        append(MEDICAL_DISCLAIMER)
    }

    fun appendToShareText(content: String): String {
        val trimmed = content.trimEnd()
        return if (trimmed.contains("Generated by $APP_NAME") &&
            trimmed.contains(DIAGNOSIS_NOTICE)
        ) {
            trimmed
        } else {
            "$trimmed\n\n${shareFooter()}"
        }
    }

    /** Comment rows keep CSV files valid while making provenance visible. */
    fun csvMetadataRows(): List<String> = listOf(
        "# Generated by $APP_NAME",
        "# $INFORMATIONAL_LABEL only — $DIAGNOSIS_NOTICE.",
        "# $MEDICAL_DISCLAIMER"
    )
}
